import Head from 'next/head'
import Image from 'next/image'
import React, {useEffect} from 'react'
import Navbar from '../component/Navbar'
import styles from '../styles/Home.module.css'
import Aos from "aos";
import "aos/dist/aos.css";

export default function Home() {
  useEffect(() => {
    Aos.init({ duration: 1000 });
  }, []);
  return (
    <div>
      <Head>
        <title>Tani&apos;s Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Navbar/>
      
      <div className={styles.container}>

      <div className={styles.bg1}>
            <div className={styles.rotate} >    
             <div className={styles.line}></div>
             <h1>Welcome to the <br/>world of Tasty & <br/>Fresh Food.</h1>
             </div>

             <div className={styles.main} data-aos='zoom-in'> 
              <h1>TANI&apos;S</h1>
              <h2>RESTAURANT</h2>
             </div>
       </div>

          <div className={styles.bg2}> </div>

      </div>


    </div>
  )
}
